import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fbf9f6',
        'surface-dim': '#dbdad7',
        'surface-bright': '#fbf9f6',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3f0',
        'surface-container': '#efeeeb',
        'surface-container-high': '#eae8e5',
        'surface-container-highest': '#e4e2df',
        'surface-variant': '#e4e2df',
        'surface-tint': '#5f5e5e',
        'on-surface': '#1b1c1a',
        'on-surface-variant': '#444748',
        'inverse-surface': '#30312f',
        'inverse-on-surface': '#f2f0ed',
        outline: '#747878',
        'outline-variant': '#c4c7c7',
        primary: '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#1c1b1b',
        'on-primary-container': '#858383',
        'inverse-primary': '#c9c6c5',
        secondary: '#635d56',
        'on-secondary': '#ffffff',
        'secondary-container': '#e7ded5',
        'on-secondary-container': '#67625a',
        tertiary: '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#1b1c1a',
        'on-tertiary-container': '#858481',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e5e2e1',
        'primary-fixed-dim': '#c9c6c5',
        'on-primary-fixed': '#1c1b1b',
        'on-primary-fixed-variant': '#474646',
        'secondary-fixed': '#eae1d8',
        'secondary-fixed-dim': '#cdc5bc',
        'on-secondary-fixed': '#1f1b15',
        'on-secondary-fixed-variant': '#4b463f',
        'tertiary-fixed': '#e5e2df',
        'tertiary-fixed-dim': '#c8c6c3',
        'on-tertiary-fixed': '#1b1c1a',
        'on-tertiary-fixed-variant': '#474744',
        background: '#fbf9f6',
        'on-background': '#1b1c1a',
        gold: {
          400: '#e5b869',
          500: '#d4a34b',
          600: '#b8862d',
        },
      },
      spacing: {
        'space-2xs': '0.25rem',
        'space-xs': '0.5rem',
        'space-sm': '0.75rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2rem',
        'space-2xl': '3rem',
        'space-3xl': '4.5rem',
        'space-4xl': '6rem',
        'gutter-mobile': '1rem',
        'gutter-tablet': '1.5rem',
        'gutter-desktop': '2.5rem',
        'margin-mobile': '1.25rem',
        'margin-tablet': '2.5rem',
        'margin-desktop': '4rem',
      },
      fontFamily: {
        serif: ['var(--font-bodoni)', 'Bodoni Moda', 'Georgia', 'serif'],
        sans: ['var(--font-inter)', 'Inter', 'system-ui', 'sans-serif'],
        'display-hero': ['var(--font-bodoni)', 'Bodoni Moda', 'serif'],
        'display-hero-mobile': ['var(--font-bodoni)', 'Bodoni Moda', 'serif'],
        'headline-lg': ['var(--font-bodoni)', 'Bodoni Moda', 'serif'],
        'headline-lg-mobile': ['var(--font-bodoni)', 'Bodoni Moda', 'serif'],
        'headline-md': ['var(--font-bodoni)', 'Bodoni Moda', 'serif'],
        'headline-sm': ['var(--font-bodoni)', 'Bodoni Moda', 'serif'],
        'title-editorial': ['var(--font-bodoni)', 'Bodoni Moda', 'serif'],
        'body-lg': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'body-sm': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'label-caps-lg': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'label-caps-sm': ['var(--font-inter)', 'Inter', 'sans-serif'],
        'numeric-data': ['var(--font-inter)', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'display-hero-mobile': ['38px', { lineHeight: '46px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-sm': ['22px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '500' }],
        'title-editorial': ['18px', { lineHeight: '24px', letterSpacing: '0.02em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '0.01em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '0.01em', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '400' }],
        'label-caps-lg': ['12px', { lineHeight: '16px', letterSpacing: '0.14em', fontWeight: '600' }],
        'label-caps-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.18em', fontWeight: '600' }],
        'numeric-data': ['13px', { lineHeight: '18px', letterSpacing: '0.04em', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};

export default config;
